version: "3.7"
services:
  emby:
    image: ghcr.io/linuxserver/emby
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/ced/emby:/config
      - /media/tvshows:/data/tvshows
      - /media/movies:/data/movies
    ports:
      - 8196:8096
      - 8820:8920 #optional
    restart: unless-stopped
    
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/ced/jellyfin:/config
      - /media/tvshows:/data/tvshows
      - /media/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
  
  prowlarr:
    container_name: prowlarr
    image: linuxserver/prowlarr:develop
    ports:
      - "9696:9696"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Toronto
    volumes:
      - /home/ced/prowlarr:/config
    restart: unless-stopped
      
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/ced/sonarr:/config
      - /media/tvshows:/tv #optional
      - /media/downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /home/ced/radarr:/config
      - /media/movies:/movies #optional
      - /media/downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/ced/deluge:/config
      - /media/downloads:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
